name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CSV_URL: "project/train_data.csv"
  TARGET_VAR: "Loan_Status"
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.7"

      # Install Dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools==68.0.0 wheel==0.41.2
          pip install mlflow==2.11.3 dagshub scikit-learn pandas numpy

      # Set MLflow Tracking
      - name: Configure MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/alyafauziaaz20/mlflow-CI-Submis.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USER }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      # Run Training
      - name: Run MLflow Project
        run: |
          python project/modelling.py

      - name: Read run_id from file
        run: |
          RUN_ID=$(cat run_id.txt)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Run ID Loaded: $RUN_ID"

      # Upload to Google Drive
      - name: Install GDrive libraries
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload MLflow Artifacts to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python project/upload_to_gdrive.py
          echo "Success upload model to Google Drive"

      # Build Docker Model
      - name: Build Docker Model
        run: |
          echo "Building docker model for run: $RUN_ID"
          mlflow models build-docker --model-uri "runs:/${RUN_ID}/model" --name "submis-mlflow"

      # Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Images
        run: |
          docker tag submis-mlflow ${{ secrets.DOCKER_HUB_USERNAME }}/submis-mlflow:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/submis-mlflow:latest
