name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CSV_URL: "project/train_data.csv"
  TARGET_VAR: "Loan_Status"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.7"

      # 3. Install ML & data dependencies
      - name: Install ML dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub scikit-learn pandas numpy

      # 4. Set MLflow Tracking to DagsHub
      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/alyafauziaaz20/mlflow-CI-Submis.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USER }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      # 5. Run training script
      - name: Run MLflow Project (modelling)
        run: |
          python project/modelling.py

      # 6. Install Google Drive dependencies
      - name: Install GDrive libraries
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # 7. Upload model to Google Drive + commit CI result
      - name: Upload MLflow artifacts to Google Drive & Commit
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python project/upload_to_gdrive.py
          
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          
          git add .
          git commit -m "CI run successful â€” MLflow project executed!" || echo "No changes to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/ayalya/mlflow-CI-Submis.git main