name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CSV_URL: "project/train_data.csv"
  TARGET_VAR: "Loan_Status"
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.7"

      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install Dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools==68.0.0 wheel==0.41.2
          pip install mlflow==2.11.3 dagshub scikit-learn pandas numpy

      # Set MLflow Tracking
      - name: Configure MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/alyafauziaaz20/mlflow-CI-Submis.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USER }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      # Run Training
      - name: Run MLflow Project
        run: |
          python project/modelling.py

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Upload to Google Drive
      - name: Install GDrive libraries
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload MLflow Artifacts to Google Drive & Commit
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python project/upload_to_gdrive.py
          
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

          echo "Sucess upload model to gd"

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/#RUN_ID" --name "cc"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: |
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Tag Docker Images
        run: |
          docker tag submis-mlflow ${{ secrets.DOCKER_HUB_USERNAME}}/submis-mlflow:latest
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_ACCESS_USERNAME}}/submis-mlflow:latest
        